# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-23 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='\u610f\u5411\u56fd\u5bb6')),
                ('type', models.CharField(max_length=30, verbose_name='\u610f\u5411\u5c42\u6b21')),
                ('major', models.CharField(max_length=30, verbose_name='\u610f\u5411\u4e13\u4e1a')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9ad8\u7aef\u7533\u8bf7',
                'verbose_name_plural': '\u9ad8\u7aef\u7533\u8bf7',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=300, verbose_name='\u95ee\u9898')),
                ('answer', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u56de\u7b54')),
                ('teacher', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u56de\u7b54\u8005')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u63d0\u95ee\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u95ee\u9898',
                'verbose_name_plural': '\u7528\u6237\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(default=0, verbose_name='\u7c7b\u578bid')),
                ('store_type', models.IntegerField(choices=[(1, '\u6587\u4e66'), (2, '\u7b7e\u8bc1')], default=1, verbose_name='\u8d2d\u7269\u8f66\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u52a0\u5165\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Major', verbose_name='\u4e13\u4e1a')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='\u5b66\u6821')),
            ],
            options={
                'verbose_name': '\u7533\u8bf7\u4e13\u4e1a',
                'verbose_name_plural': '\u7533\u8bf7\u4e13\u4e1a',
            },
        ),
    ]
