# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170623_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='highapply',
            name='real_name',
            field=models.CharField(max_length=40, null=True, verbose_name='\u59d3\u540d'),
        ),
    ]
