# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_highapply_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='status',
            field=models.IntegerField(choices=[(1, '\u5df2\u89e3\u51b3'), (0, '\u672a\u89e3\u51b3')], default=0),
        ),
    ]
