# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-23 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7b7e\u8bc1\u540d\u79f0')),
                ('english_name', models.CharField(max_length=50, verbose_name='\u82f1\u6587\u540d')),
                ('image', models.ImageField(upload_to='visa', verbose_name='\u5c01\u9762')),
                ('type', models.CharField(choices=[(b'xs', '\u5b66\u751f\u7b7e\u8bc1'), (b'ly', '\u65c5\u6e38\u7b7e\u8bc1'), (b'ye', '1+2\u5957\u9910'), (b'bg', '\u5305\u8fc7\u5957\u9910')], max_length=8, verbose_name='\u7b7e\u8bc1\u7c7b\u578b')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u63cf\u8ff0')),
                ('price', models.FloatField(default=0, verbose_name='\u4ef7\u683c')),
            ],
            options={
                'verbose_name': '\u7b7e\u8bc1',
                'verbose_name_plural': '\u7b7e\u8bc1',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6587\u4e66\u540d\u79f0')),
                ('english_name', models.CharField(max_length=50, verbose_name='\u82f1\u6587\u540d')),
                ('image', models.ImageField(upload_to='writer', verbose_name='\u5c01\u9762')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u63cf\u8ff0')),
                ('price', models.FloatField(default=0, verbose_name='\u4ef7\u683c')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='\u8be6\u60c5')),
                ('service', models.TextField(blank=True, null=True, verbose_name='\u670d\u52a1\u4fdd\u969c')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u4e66',
                'verbose_name_plural': '\u6587\u4e66',
            },
        ),
        migrations.CreateModel(
            name='WriteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('desc', models.CharField(max_length=150, verbose_name='\u7c7b\u578b\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u4e66\u7c7b\u578b',
                'verbose_name_plural': '\u6587\u4e66\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='writer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.WriteType', verbose_name='\u6587\u4e66\u7c7b\u578b'),
        ),
    ]
