# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_visa_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7b7e\u8bc1\u7c7b\u578b',
                'verbose_name_plural': '\u7b7e\u8bc1\u7c7b\u578b',
            },
        ),
        migrations.RemoveField(
            model_name='writetype',
            name='desc',
        ),
    ]
