# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-23 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u56fd\u5bb6\u540d\u79f0')),
                ('desc', models.CharField(max_length=150, verbose_name='\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fd\u5bb6',
                'verbose_name_plural': '\u56fd\u5bb6',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4e13\u4e1a\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e13\u4e1a\u63cf\u8ff0')),
                ('type', models.CharField(choices=[(b'college', '\u672c\u79d1'), (b'graduate', '\u7814\u7a76\u751f')], default=b'college', max_length=15)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a\u4fe1\u606f',
                'verbose_name_plural': '\u4e13\u4e1a\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='MajorField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='\u4e13\u4e1a\u65b9\u5411\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a\u65b9\u5411',
                'verbose_name_plural': '\u4e13\u4e1a\u65b9\u5411',
            },
        ),
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('image', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image1', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image2', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image3', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image4', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image5', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image6', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('image7', models.ImageField(upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6821\u56ed\u98ce\u5149',
                'verbose_name_plural': '\u6821\u56ed\u98ce\u5149',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u5b66\u6821\u540d\u79f0')),
                ('image', models.ImageField(max_length=200, upload_to='university', verbose_name='logo')),
                ('english_name', models.CharField(max_length=200, verbose_name='\u82f1\u6587\u540d')),
                ('city', models.CharField(max_length=100, verbose_name='\u6240\u5c5e\u57ce\u5e02')),
                ('type', models.CharField(choices=[(b'private', '\u79c1\u7acb'), (b'public', '\u516c\u7acb')], default=b'public', max_length=13)),
                ('bulid_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5efa\u6821\u65f6\u95f4')),
                ('tea_stu', models.CharField(max_length=10, verbose_name='\u5e08\u751f\u6bd4')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u4eba\u6570')),
                ('tuition', models.IntegerField(default=0, verbose_name='\u5b66\u8d39')),
                ('accept_rate', models.CharField(max_length=30, verbose_name='\u5f55\u53d6\u7387')),
                ('address', models.CharField(max_length=10, verbose_name='\u5b66\u6821\u5730\u5740')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('url', models.CharField(max_length=200, verbose_name='\u7f51\u5740')),
                ('rank', models.IntegerField(default=0, verbose_name='\u6392\u540d')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u7b80\u4ecb')),
                ('college_gpa', models.FloatField(default=75.0, verbose_name='\u672c\u79d1GPA')),
                ('college_toefl', models.FloatField(default=110.0, verbose_name='\u672c\u79d1\u6258\u798f')),
                ('college_ielts', models.FloatField(default=6.0, verbose_name='\u672c\u79d1\u96c5\u601d')),
                ('graduate_gpa', models.FloatField(default=75, verbose_name='\u7814\u7a76\u751fGPA')),
                ('graduate_toefl', models.FloatField(default=110.0, verbose_name='\u7814\u7a76\u751f\u6258\u798f')),
                ('graduate_ielts', models.FloatField(default=6.0, verbose_name='\u7814\u7a76\u751f\u96c5\u601d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Country', verbose_name='\u6240\u5c5e\u56fd\u5bb6')),
            ],
            options={
                'verbose_name': '\u5927\u5b66\u4fe1\u606f',
                'verbose_name_plural': '\u5927\u5b66\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='scenery',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='\u6240\u5c5e\u5927\u5b66'),
        ),
        migrations.AddField(
            model_name='major',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.MajorField', verbose_name='\u4e13\u4e1a\u65b9\u5411'),
        ),
    ]
