# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20170623_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='\u6240\u5c5e\u5927\u5b66'),
        ),
    ]
