# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20170623_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u82f1\u6587\u540d\u79f0'),
        ),
    ]
