# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20170627_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': '\u5b66\u5386\u5c42\u6b21', 'verbose_name_plural': '\u5b66\u5386\u5c42\u6b21'},
        ),
    ]
