# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20170627_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='desc',
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(max_length=150, null=True, upload_to='university/country/%y/%m', verbose_name='logo'),
        ),
    ]
