# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20170628_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
    ]
