# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_university_click_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='show_index',
            field=models.IntegerField(choices=[(1, '\u9996\u9875\u663e\u793a'), (0, '\u9996\u9875\u4e0d\u663e\u793a')], default=0, verbose_name='\u662f\u5426\u9996\u9875\u663e\u793a'),
        ),
    ]
