# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_university_show_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(default=b'university/logo/logo.jpg', max_length=200, upload_to='university/logo', verbose_name='\u6821\u5fbd'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(max_length=200, upload_to='university', verbose_name='\u9996\u9875\u5c55\u793a\u56fe'),
        ),
    ]
