# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_university_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(max_length=200, upload_to='university/index', verbose_name='\u9996\u9875\u5c55\u793a\u56fe'),
        ),
    ]
