# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_auto_20170712_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
    ]
