# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20170712_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenery',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='title',
        ),
    ]
