# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_auto_20170712_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenery',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='university/scenery/%y/%m', verbose_name='\u6821\u56ed\u98ce\u5149'),
        ),
    ]
