# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_auto_20170712_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenery',
            name='title',
            field=models.CharField(default=b'', max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
