# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_scenery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenery',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u9898'),
        ),
    ]
