# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-11 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20170629_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u6807\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('status', models.IntegerField(choices=[(0, '\u8349\u7a3f'), (1, '\u53d1\u5e03')], default=0, verbose_name='\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5e2e\u52a9\u4e2d\u5fc3',
                'verbose_name_plural': '\u5e2e\u52a9\u4e2d\u5fc3',
            },
        ),
    ]
